site_name: hackfun
theme:
  name: material
  palette:
    scheme: slate  # dark theme
    primary: black
    accent: lime   # hacker green
  font:
    text: Roboto Mono
    code: Fira Code
nav:
  - Walkthroughs:
    - Port Swigger:
      - Path traversal:
        - File path traversal, simple case: walkthroughs/port_swigger/path_traversal/file_path_traversal_simple_case.md
      - Access control vulnerabilities:
        - Unprotected admin functionality: walkthroughs/port_swigger/access_control_vulnerabilities/unprotected_admin_functionality.md
        - Unprotected admin functionality with unpredictable URL: walkthroughs/port_swigger/access_control_vulnerabilities/unprotected_admin_functionality_with_unpredictable_url.md
        - User role controlled by request parameter: walkthroughs/port_swigger/access_control_vulnerabilities/user_role_controlled_by_request_parameter.md
        - User ID controlled by request parameter, with unpredictable user IDs: walkthroughs/port_swigger/access_control_vulnerabilities/user_id_controlled_by_request_parameter_with_unpredictable_user_ids.md
  - Cheat-sheets:
    - General: cheat_sheets/general.md
